// packages/vue/src/components/Button.vue
<script setup lang="ts">
import { buttonVariants, type ButtonSharedProps } from '@core/components/button';


const props = withDefaults(defineProps<ButtonSharedProps>(), {
  loading: false,
  disabled: false,
  type: 'button'
})

</script>

<template>
  <button
    :type="props.type"
    :disabled="props.disabled || props.loading"
    :class="buttonVariants({
      variant: props.variant,
      size: props.size
    })"
    :data-loading="props.loading"
  >
      <span v-if="$slots.icon">
          <slot name="icon"/>
      </span>

      <slot />
  </button>
</template>

// packages/react/src/Button.tsx
import { buttonVariants, type ButtonSharedProps } from "@core/components/button";

export default function Button({
  variant,
  size,
  loading = false,
  disabled = false,
  type = "button",
  ...props
}: ButtonSharedProps) {
  return (
    <button
      type={type}
      disabled={disabled || loading}
      data-loading={loading}
      className={buttonVariants({ variant, size })}
      {...props}
    />
  );
}
